### ISSUE TITLE
Filter groups display bug

### ISSUE THREAD

**Issue by lifehaschanged** [decaf-dev/obsidian-vault-explorer#101]
I found a bug, hope it helps:
1. Open a sandbox vault with the command palette and install vault explorer plugin only
2. Add many filter groups 
3. Here you can see it cut off from filter group 5, group 6 not visible anymore:

<img width="428" alt="2024-06-23 17_52_21-Vault Explorer - Obsidian v1 6 3" src="https://github.com/decaf-dev/obsidian-vault-explorer/assets/81463128/fde66000-c652-4260-bedb-c72b355a6dd5">

**Comment by decaf-dev** [comment]
Thanks for posting this. I use a laptop that has a touch pad and I forget that you can't scroll right now when using a normal mouse.

**Comment by decaf-dev** [comment]
Fixed in 1.13.1
