### ISSUE TITLE
File icons

### ISSUE THREAD

**Issue by lifehaschanged** [decaf-dev/obsidian-vault-explorer#123]
To improve overview and better distinguish between different file formats during the filtering process, I would welcome the introduction of file icons. For example, regular markdown files could all have the same icon, while other formats like .pdf files, or other plugin extension formats like excalidraw or canvas files could even display the file icons from the extension itself, which are also shown in the tabs of these extensions. For instance, excalidraw files could show the crossed pencils icon as seen in the excalidraw tabs.
Thanks for considering it.

**Comment by decaf-dev** [comment]
Good suggestion! Do you have a screenshot of the Excalidraw functionality?

**Comment by decaf-dev** [comment]
Added in 1.21.0

**Comment by decaf-dev** [comment]
Thank you!
