### ISSUE TITLE
[FR] Filters Button Improvement

### ISSUE THREAD

**Issue by Moyf** [decaf-dev/obsidian-vault-explorer#126]
Considering the number of filters may increase, maybe consider these features?

1. <del> Support drag-and-drop for reordering. </del>
2. Right-click button to edit. 
3. (Optional) Allow users to customize the displayed width of filters in settings and add an option for wrap or not ( For now it only shows ~5 filters and others cannot be seen )

---

Edit: Just found out that now it already support Drag&Drop Re-order, just the position is kind of confusing 😂
I originally thought I should drag into the middle position, but it turned out I need to drag on the button lol
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/bbe543cc-3750-47ee-8da6-52ff8528e392)

**Comment by decaf-dev** [comment]
Added resizing and wrapping in 1.22.0

**Comment by decaf-dev** [comment]
Update the wrap setting. Added scroll bar for accessibility. Added right click to edit. All added in 1.31.0. Thank you for the suggestions.

**Comment by Moyf** [comment]
> Updated the wrap setting. Added a scroll bar for accessibility. Added right click to edit. All added in 1.31.0. Thank you for the suggestions.

![image](https://github.com/user-attachments/assets/451e11e8-ef92-42b2-9bfb-9579cf2a8a15)

Hi! May I ask if the style of this badge could be changed?
I personally prefer the previous style 😃

( Is this an HTML built-in attribute of textarea or do we have any way - like css - to modify it? )
