### ISSUE TITLE
[Feedback] Refresh result when changing filter

### ISSUE THREAD

**Issue by Moyf** [decaf-dev/obsidian-vault-explorer#138]
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/c7fd2640-6a20-4c76-90aa-8be085e581d3)

For instance, if I navigate to page 4 ( 201~250 ) and then toggle a new filter, resulting in less than 200 items (only 39),  there will be no content displayed.
Initially, I assumed the feature was malfunctioning, but later realized that I needed to click on the "First page" button to return to the initial page.

Perhaps consider implementing a feature that **automatically redirects to the first page if the new filter results in fewer items** than the current page displays?

---

Additionally, could you please ensure **the placement of the pagination buttons remains consistent**?
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/2f45c569-fe6f-4579-831f-238ba57e00cb)

This way, users can easily click on the buttons without having to readjust the mouse position.

Because for now the position would change with the page number:
![95ddacd0-028c-4552-a413-1a4cfdbc3001](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/eb0802dc-2b75-4a67-b54d-ab9dc798c12b)

**Comment by decaf-dev** [comment]
Thanks for catching this

**Comment by decaf-dev** [comment]
Fixed both issues in 1.18.2

**Comment by Moyf** [comment]
So many updates, what a pleasan surprise!
Thanks for your hard work on the development!! <3
