### ISSUE TITLE
Filtering hierarchical tags

### ISSUE THREAD

**Issue by Accelsnow** [decaf-dev/obsidian-vault-explorer#157]
What is the right way to filter a hierarchical tag? For example, I have a class of tags in the following format:

- rating/T0
- rating/T1
- rating/T2
- rating/TU

I can create a tag filter for `rating`, and it will correctly display all pages with any one of the above tags. However, when I create a tag filter for either `T2` or `rating/T2`, nothing shows up. 

Screenshot for working `rating` filter:
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/36573521/0dee2790-feca-44eb-9838-f2201a2dbb19)

Screenshot for not working `rating/T2` filter:
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/36573521/4dabe4d6-210d-48c9-b544-bd9262f49876)

Screenshot for not working `T2` filter:
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/36573521/a26651ed-d5e8-4905-a1b6-9713b82fc6a6)

I've also tried numerous "common" ways to escape the `/` character and still no luck. What am I doing wrong here?

**Comment by decaf-dev** [comment]
Hi @Accelsnow. Let me take a look at this. I am not sure why it isn't working

**Comment by decaf-dev** [comment]
Okay. It should be fixed in 1.21.1. Please upgrade your plugin version :)

**Comment by decaf-dev** [comment]
Right now all filters are case insensitive. So `rating/T1` or `rating/t1` will work.

**Comment by Accelsnow** [comment]
Can confirm that the fix works! That was a fast fix thanks!
