### ISSUE TITLE
Documentation on Tag filtering

### ISSUE THREAD

**Issue by Eflores89** [decaf-dev/obsidian-vault-explorer#24]
First, thanks for this very cool and useful plugin. 

One thing I have struggled with is getting the tag filtering to work. For example, if I add two conditions, are they an "AND" or "OR" condition? Does this persist with any type of property and across properties? Do I need to add quotations or `#` to the tag? Does the tag include subtags (e.g., are you doing `econtains` or `contains` in the background)?

I think some more documentation on this would be useful.

**Comment by trey-wallis** [comment]
Hey @Eflores89. I haven't gotten around to making documentation for this yet.

For two conditions, they should be AND. I will add the AND or OR select options next.

Does it persist with any of type of property? I don't know what you mean by that?

You do not need to add quotations or # to the tag. Just use plain text.

No, subtags aren't working right now. That's something that can be added

**Comment by trey-wallis** [comment]
For multiple tag filtering, separate by a comma `tag1,tag2`

**Comment by trey-wallis** [comment]
It seems like it is set to OR by default right now, that is not intended.

**Comment by decaf-dev** [comment]
@Eflores89 Okay. I have fixed the behavior in 1.4.1. I have added the `and`,`or` filter operators and fixed the behavior for list property filtering. It now supports subtags. I will add documentation in the near future. I am going to close this issue.
