### ISSUE TITLE
Cover image fill 

### ISSUE THREAD

**Issue by decaf-dev** [decaf-dev/obsidian-vault-explorer#244]
Also, I hope that the Grid view supports displaying the first image in the note, not just the image link in the `image` attribute. 
And I hope that images can be set to display in a specific way: constrain(maintain aspect ratio) or fill (horizontally tile):
![image](https://github.com/user-attachments/assets/c9746239-6186-4a4c-aa0a-816149a57abc)

![image](https://github.com/user-attachments/assets/6099605c-3b2a-41ff-b63f-5bacf111489e)

---

Additionally, I would like to provide an alternative option to display using `title` instead of the file name. But this one is not very important I think... 🤔

_Originally posted by @Moyf in https://github.com/decaf-dev/obsidian-vault-explorer/issues/40#issuecomment-2230951554_

**Comment by decaf-dev** [comment]
@moyf Do you already have a property configured for your vault for "fill"?

**Comment by Moyf** [comment]
> @Moyf Do you already have a property configured for your vault for "fill"?

I have an `image` property, but most of my notes just use the **first image in note**.

And now I see the image is filled, you have added this feature already?
![image](https://github.com/user-attachments/assets/4b4b82c0-e681-44c1-ac73-4557be3959eb)

**Comment by decaf-dev** [comment]
@Moyf I use the `object-fit` property. It is set to `cover`. However, this might not be the best display for all images.

**Comment by decaf-dev** [comment]
@Moyf Added in 1.41.0.
