### ISSUE TITLE
Social media image not loading

### ISSUE THREAD

**Issue by decaf-dev** [decaf-dev/obsidian-vault-explorer#265]
Hi! I found that if I set the `url` in frontmatter:
![image](https://github.com/user-attachments/assets/ce035aa5-c90c-4e01-a823-d8eeab23caef)

it will show a broken image:
![image](https://github.com/user-attachments/assets/471e722b-c4fb-4519-9c5f-f9874ef7c732)

I checked the dev tool and **the image url itself is correct**, I can open it in my browser. 
I guess it might be due to some access restriction of this website.

> If you want to test, here is the url: `https://www.bilibili.com/video/BV1MU411S7qZ/`

And then I turn of the **Load social media image** in setting:
![image](https://github.com/user-attachments/assets/03a1fa3f-4fe5-476b-88ed-ab57ecebaeb5)

Then it just show nothing - even I got images in my note and hope to show the first image in body.

If there is some fallback mechanism it would be better.

> my plugin version: 1.32.2

**Comment by decaf-dev** [comment]
@moyf I have pushed a fixed for the bilibili url. Please clear the social media cache and then close and reopen vault explorer. It should load properly :)

<img width="1096" alt="image" src="https://github.com/user-attachments/assets/9a16a594-8029-43ac-a5f8-26eedb1cc933">

**Comment by Moyf** [comment]
> @Moyf I have pushed a fixed for the bilibili url. Please clear the social media cache and then close and reopen vault explorer. It should load properly :)
> 
> <img alt="image" width="1096" src="https://private-user-images.githubusercontent.com/40307803/352694320-9a16a594-8029-43ac-a5f8-26eedb1cc933.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNTQ5MzUsIm5iZiI6MTcyMjA1NDYzNSwicGF0aCI6Ii80MDMwNzgwMy8zNTI2OTQzMjAtOWExNmE1OTQtODAyOS00M2FjLWE1ZjgtMjZlZWRiMWNjOTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA0MzAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZmVkNmUyNzQxMDg1OGM0MGY5OTY4NmM0M2UyZWFiNTcyY2VjNGU4MDc3ZjA3NTZjNWY4MTFjM2JjYjc3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SgLCF8PFcItJPpG2ezrJn7NXMitSN8KC5q17MIeYR1g">

Wow great, thank you!

By the way, I used to use [Plugin update tracker](https://github.com/swar8080/obsidian-plugin-update-tracker) to track and update my plugins. But with VE, it can not track the update info.
While in Community Plugin it can see the `Update` button. Do you have ideas why ?

**Comment by Moyf** [comment]
I've updated to new version (1.35.0) and the image of bilibili can be displayed!

Just the resolution is kind of low..
![image](https://github.com/user-attachments/assets/65ecf20c-c5fd-4178-a9af-f27c3accbaca)

🤔 I check in the dev tool and there is a "@100w_100h_1c" suffix. I guess that't why resolution is low (only 100x100)?
![image](https://github.com/user-attachments/assets/d966b6fa-4418-4426-a71c-dbe23ab14780)


---

Not important but just mention, in this version license area became empty (though I can still use the premium functions)
![image](https://github.com/user-attachments/assets/e5407bb8-2eef-4e44-a4a4-02db82329912)

**Comment by Moyf** [comment]
> I've updated to new version (1.35.0) and the image of bilibili can be displayed!
> 
> Just the resolution is kind of low.. ![image](https://private-user-images.githubusercontent.com/4013062/352699775-65ecf20c-c5fd-4178-a9af-f27c3accbaca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNTcxNDcsIm5iZiI6MTcyMjA1Njg0NywicGF0aCI6Ii80MDEzMDYyLzM1MjY5OTc3NS02NWVjZjIwYy1jNWZkLTQxNzgtYTlhZi1mMjdjM2FjY2JhY2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjdUMDUwNzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGExOTNmODVmZmEzYWQzZjg3NDE5OTBlMzZjMTliOGY2ZjMxYzQ4ZGM5NGFjY2E4ZjA4Zjc5ZGFjZDRmMjkwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WviaxAxOacdpI4yDq4kRiLiG284BE0QLVZ0mWvQoPaM)
> 
> 🤔 I check in the dev tool and there is a "@100w_100h_1c" suffix. I guess that't why resolution is low (only 100x100)? ![image](https://private-user-images.githubusercontent.com/4013062/352699792-d966b6fa-4418-4426-a71c-dbe23ab14780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNTcxNDcsIm5iZiI6MTcyMjA1Njg0NywicGF0aCI6Ii80MDEzMDYyLzM1MjY5OTc5Mi1kOTY2YjZmYS00NDE4LTQ0MjYtYTcxYy1kYmUyM2FiMTQ3ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjdUMDUwNzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTI3MjI0MTZhMWYwMzAxODVlNjdjZDhmMjYzNmYzYTA2OGFhNWE3ZTYyOGJkOTRmZjE5YTA0NDIyNDg0ODI3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LF6UaLZsdWL8j7zyLJGgOrXw1X5OFIVhpYzkEI4BCGs)
> 
> Not important but just mention, in this version license area became empty (though I can still use the premium functions) ![image](https://private-user-images.githubusercontent.com/4013062/352699847-e5407bb8-2eef-4e44-a4a4-02db82329912.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNTcxNDcsIm5iZiI6MTcyMjA1Njg0NywicGF0aCI6Ii80MDEzMDYyLzM1MjY5OTg0Ny1lNTQwN2JiOC0yZWVmLTRlNDQtYTRhNC0wMmRiODIzMjk5MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjdUMDUwNzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDFlZDVmZDliMmY5Njc0ZjlhNGQ3ODc2ZDE1OWJjZWEwMWQ4MjAyODMzYWVkZmY0MzNiOGRiNWMyNGQzOTkxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Rt-puy07Rtd5oLlyDyUNBJQPQAw8YPrIkiMIePEzwB4)

Oh no, the premium function itself is also gone 
![image](https://github.com/user-attachments/assets/aded090e-90b6-49dc-824f-cc06630ec12f)

**Comment by decaf-dev** [comment]
> Plugin update tracker

I have never heard of this plugin. I don't have any idea why it wouldn't appear. I follow the community plugin standards for versioning

**Comment by decaf-dev** [comment]
For the license key, that's odd. I didn't change anything related to that. Can you try restarting Obsidian?

**Comment by decaf-dev** [comment]
@Moyf The low quality image should be fixed. Please upgrade to 1.35.1, clear the social media cache and close and reopen Vault Explorer.

**Comment by Moyf** [comment]
> For the license key, that's odd. I didn't change anything related to that. Can you try restarting Obsidian?

I've just re-entered the lisence to re-enable the premium version.
( Don't know would it consume my device number? )

**Comment by decaf-dev** [comment]
> > For the license key, that's odd. I didn't change anything related to that. Can you try restarting Obsidian?
> 
> I've just re-entered the lisence to re-enable the premium version. ( Don't know would it consume my device number? )

I just checked the backend. If you had 2 devices registered before, then no. You have 3 more devices available

**Comment by Moyf** [comment]
> > > For the license key, that's odd. I didn't change anything related to that. Can you try restarting Obsidian?
> > 
> > 
> > I've just re-entered the lisence to re-enable the premium version. ( Don't know would it consume my device number? )
> 
> I just checked the backend. If you had 2 devices registered before, then no. You have 3 more devices available

Yes, I have one in home and one in corp, then all is well 😄

**Comment by Moyf** [comment]
> @Moyf The low quality image should be fixed. Please upgrade to 1.35.1, clear the social media cache and close and reopen Vault Explorer.

1.35.1 fixed it ! 👍🏻
