### ISSUE TITLE
Header anchor appears as a tag

### ISSUE THREAD

**Issue by decaf-dev** [decaf-dev/obsidian-vault-explorer#292]
## Problem
When you have an internal embed to a markdown note with an header (a block reference or header link), the header will be processed as a body tag.

## Expected behavior
Ignore the header anchor

## Steps to reproduce
1. Create a note with a level 1 header
2. Create another note
3. Make an internal embed with a reference to the header`![[note#header]]
4. See the #header appear as a tag for the note file in all views

**Comment by Moyf** [comment]
Also found other situations:
![image](https://github.com/user-attachments/assets/c39fcc30-6032-43a7-8ffb-7d07f5058c8c)
![image](https://github.com/user-attachments/assets/fcacdc3c-c5e6-4cfc-b1d5-8a9a13f89fc6)

Those text would also be recognized as tag:
![image](https://github.com/user-attachments/assets/bdb38f88-8223-4db4-872e-18e8631a2d5f)

Maybe use ` #xxx ` (With whitespaces around) to detect tag ?

---

BTW, could you add a setting to switch on/off "Display the tags in body" ?

**Comment by decaf-dev** [comment]
@Moyf Thanks for posting that. I will fix this soon.

**Comment by decaf-dev** [comment]
@Moyf There should be a setting already. "Load tags from body".  It was added several versions ago

**Comment by decaf-dev** [comment]
@Moyf Fixed in 1.41.1
