### ISSUE TITLE
TypeError: v.toLowerCase is not a function

### ISSUE THREAD

**Issue by Accelsnow** [decaf-dev/obsidian-vault-explorer#298]
When opening Vault Explorer, nothing shows up and Console shows the following error:

![image](https://github.com/user-attachments/assets/4a0803e0-d307-479d-a267-94b5e080f708)

Plugin Version: 1.39.0
Obsidian Version: 1.6.7

**Comment by decaf-dev** [comment]
Hey @Accelsnow. Could you click on the hyperlink where it says `filterByPropertyValue` and take a screenshot?

**Comment by decaf-dev** [comment]
@Accelsnow Please upgrade to 1.40.0. I may have fixed it.

**Comment by Accelsnow** [comment]
Sorry for the late reply. I can confirm this problem is fixed in 1.40.2 (latest version as I pull)!
