### ISSUE TITLE
Pin Vault Explorer

### ISSUE THREAD

**Issue by a-rock-lobster** [decaf-dev/obsidian-vault-explorer#313]
Doesn't currently seem to be possible to pin the Vault Explorer tab. Might be a nice addition.

**Comment by XU-Nuo** [comment]
I think you can combine it with the homepage plugin with custom command to get similar result.
![image](https://github.com/user-attachments/assets/870b6f03-b08b-4180-9a7a-d8ada4d56e57)

**Comment by a-rock-lobster** [comment]
Hmm, thanks for the suggestion but I couldn't get it to work. Perhaps there is a conflict going on with another addon that effects tabs.

**Comment by decaf-dev** [comment]
@a-rock-lobster I didn't know pinning tabs was a thing. I will look into this.

**Comment by a-rock-lobster** [comment]
<img width="348" alt="Screenshot 2024-09-10 at 14 21 27" src="https://github.com/user-attachments/assets/ce6cf90c-3356-41a7-9977-ee377ee0af61">

I added a little css snippet to make pinned tabs smaller like firefox. Good space saver.

**Comment by decaf-dev** [comment]
@a-rock-lobster So I did some investigation yesterday and, I think this might be a limitation of the `ItemView` in Obsidian. If you know any plugins that have a pinnable view, let me know and I will check our their code.

**Comment by a-rock-lobster** [comment]
The [Kanban plugin](https://github.com/mgmeyers/obsidian-kanban) springs to mind. Otherwise I will keep my eye out and report back.

**Comment by decaf-dev** [comment]
I just got a response from Liam on the forums. Apparently there's a
`navigation` flag for the `View` class that can be set to true.

**Comment by decaf-dev** [comment]
@a-rock-lobster Added in 1.44.0. Enjoy :)

**Comment by a-rock-lobster** [comment]
Hey, thanks. Can report it works well. Cheers, again!
