### ISSUE TITLE
'Load tags from body' grabs anything with prefixed with # even if not a tag

### ISSUE THREAD

**Issue by a-rock-lobster** [decaf-dev/obsidian-vault-explorer#314]
Not really an issue for me as I have the 'Load tags from body' feature turned off, but I noticed that there were lots of seemingly random tags consisting of numbers being picked up from somewhere. Then I realised they are from the citations keys I use. For example, the citation {Röpke, 2014, #110328} in a note results in #110328 being shown as a tag in the Vault Explorer. Obsidian isn't treating #110328 as a tag, it's just text.

**Comment by decaf-dev** [comment]
@a-rock-lobster Fixed in 1.41.1
