### ISSUE TITLE
Show image at grid mode

### ISSUE THREAD

**Issue by nyssance** [decaf-dev/obsidian-vault-explorer#32]
I would greatly appreciate it if the grid mode could display the first image in the note or an image specified by property.

**Comment by decaf-dev** [comment]
That sounds like a great feature. It will be added in the next couple releases

**Comment by a-rock-lobster** [comment]
If this feature was compatible with the [banners](https://github.com/noatpad/obsidian-banners) plugin that would be super cool

**Comment by decaf-dev** [comment]
@nyssance Link hover preview has been added in 1.5.0. Hopefully that is a helpful temporary solution as I work on this feature.

**Comment by decaf-dev** [comment]
Added in 1.22.0.
