### ISSUE TITLE
vault-explorer issue with tray plugin

### ISSUE THREAD

**Issue by Ske-Man1149** [decaf-dev/obsidian-vault-explorer#35]
https://github.com/decaf-dev/obsidian-vault-explorer/assets/128849789/4b40fbf6-e218-459d-8381-fb4c242871cc

**Comment by Ske-Man1149** [comment]
https://github.com/decaf-dev/obsidian-vault-explorer/assets/128849789/4b40fbf6-e218-459d-8381-fb4c242871cc

**Comment by decaf-dev** [comment]
Hi. Could you explain what just happened?

**Comment by Ske-Man1149** [comment]
There is a plugin called tray give obsidian a option to be a startup app in windows . When i turn it off the issue gone .

**Comment by Ske-Man1149** [comment]
When i click to the note in the V-Explorer plugin page the tray plugin hide obsidian app in little obsidian icon in taskbar

**Comment by decaf-dev** [comment]
@Ske-Man1149 Did you find a solution to this? I just tried it on MacOS and didn't get that behavior. I do not have a Windows machine to test on.

**Comment by Ske-Man1149** [comment]
@decaf-dev after the new update the issue gone ,so i closed it by the way. Thx man 🙃 i am very grateful .
