### ISSUE TITLE
[BUG]long titles not supported

### ISSUE THREAD

**Issue by dev-araujo** [decaf-dev/obsidian-vault-explorer#46]
It appears that the current layout does not support long titles

![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/97068163/112b18ab-d138-442a-80f5-cf8cce857541)

**Comment by decaf-dev** [comment]
Fixed in 1.2.1. Please go to the settings and change `Title Wrapping` from `normal` to `break-word`
