### ISSUE TITLE
[FR] Customize the Modified/Created Date Property

### ISSUE THREAD

**Issue by Moyf** [decaf-dev/obsidian-vault-explorer#58]
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/16cc627e-edfb-4d1e-9f33-062f915cf501)

Hi! my vault is synced between different Devices, so the file's own modified/created date might be not precise.

Instead, I use my own property ( `modified_date` / `create_date` ) to store the correct date data.
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/7cac9336-a1ca-4803-a977-95f4003fbc70)

So, could Vault Explorer provide an option to customize the Data Source by reading my specific Properties rather than using the file's date?

**Comment by decaf-dev** [comment]
Hi @Moyf. Thanks for the feature request. I like this idea. I actually have some notes that use a date property like the ones that you described. This is something that definitely can be added.

**Comment by Moyf** [comment]
> Hi @Moyf. Thanks for the feature request. I like this idea. I actually have some notes that use a date property like the ones that you described. This is something that definitely can be added.

I am honored to be accepted, thank you!

**Comment by decaf-dev** [comment]
Added in 1.6.0.
