### ISSUE TITLE
Filter-by-tag support

### ISSUE THREAD

**Issue by Accelsnow** [decaf-dev/obsidian-vault-explorer#64]
Just tried the plugin and loved the concept. It's a nice way to visualize my notes.

I just have one question (potentially suggestion). Is it possible to filter notes by tags? I see options to filter by folder, date and properties, but not tags. It would be helpful as I use tags extensively in my notes and want to be able to filter-by-tag alongside with other filters (like properties). Is it something that is part of the TODOs?

Plugin version: 1.7.0
Obsidian version: 1.6.3

Cheers!

**Comment by Accelsnow** [comment]
My apologies I did not notice that tags are under the list property filters. But yes I do use in-file tags quite extensively (together with frontmatter tags). Just wondering if in-file tags something WIP?

**Comment by decaf-dev** [comment]
Added in 1.10.0.
