### ISSUE TITLE
[FR] Support more timedate formats

### ISSUE THREAD

**Issue by Moyf** [decaf-dev/obsidian-vault-explorer#65]
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/a39e4035-1f0d-4521-afde-00ed9926e575)

`"YYYY-MM-DDTHH:mm"`
Hope to support this kind of date format  : )

**Comment by Moyf** [comment]
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/9a7ad472-8da0-450e-b6f3-6c18e705b720)

Oh.. And it seems that we would need a way to ignore specific folders (like Templater's folder) to avoid this kind of problem

**Comment by decaf-dev** [comment]
Hey @Moyf. Thanks for finding this. I will add the other format.

**Comment by decaf-dev** [comment]
That's interesting. I will ignore the templater strings as well. Thanks for catching that

**Comment by decaf-dev** [comment]
> ![image](https://private-user-images.githubusercontent.com/4013062/338444458-9a7ad472-8da0-450e-b6f3-6c18e705b720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODM3NDYsIm5iZiI6MTcxODA4MzQ0NiwicGF0aCI6Ii80MDEzMDYyLzMzODQ0NDQ1OC05YTdhZDQ3Mi04ZGEwLTQ1MGUtYjZmMy02YzE4ZTcwNWI3MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDUyNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjgzYTc1YmNlNTdiMjQzYmQxMTlhOWM1MTAwNjY1ODk0ZDRlYzFlYjQ2YTdjOTEzNjM0YTRhMTM2NzVkMjBlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c9cvlJ9Jo8JrEMG6ONez_uxBYTd8deppGejxqa5pyMI)
> 
> Oh.. And it seems that we would need a way to ignore specific folders (like Templater's folder) to avoid this kind of problem

Do you have a frontmatter property set to `date` or `datetime` with that templater string?

**Comment by Moyf** [comment]
> > <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/4013062/338444458-9a7ad472-8da0-450e-b6f3-6c18e705b720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODM3NDYsIm5iZiI6MTcxODA4MzQ0NiwicGF0aCI6Ii80MDEzMDYyLzMzODQ0NDQ1OC05YTdhZDQ3Mi04ZGEwLTQ1MGUtYjZmMy02YzE4ZTcwNWI3MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDUyNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjgzYTc1YmNlNTdiMjQzYmQxMTlhOWM1MTAwNjY1ODk0ZDRlYzFlYjQ2YTdjOTEzNjM0YTRhMTM2NzVkMjBlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c9cvlJ9Jo8JrEMG6ONez_uxBYTd8deppGejxqa5pyMI">
> > Oh.. And it seems that we would need a way to ignore specific folders (like Templater's folder) to avoid this kind of problem
> 
> Do you have a frontmatter property set to `date` or `datetime` with that templater string?

Yay, actually it's my basic template for all of my notes, so it would use the global frontmatters:
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/2a71f8b2-8a91-4647-8cce-996145abbae0)

---

When I set the new custom datetime property in Settings, I discovered that some early notes with non-standard dates could prevent the plugin from running, resulting in all content being displayed as blank. I used Batch Search & Replace in VSCode to correct this issue. However, would it be more convenient to display a warning, ignore the file, and continue the process instead of throwing an error and blocking subsequent scans, which leads to no content being displayed?

**Comment by Moyf** [comment]
When it comes to time, I also want to know what format should be used when filling in the date for the `date/datetime` filter with "is after" condition?
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/dc111f0e-050e-49de-9bb0-485868339cc3)
(Is it possible to add a date selection button later? )

Also, can it support adaptive dates like 1d (1 day) or 2w (2 weeks) instead of entering a fixed date?

**Comment by decaf-dev** [comment]
I thought Obsidian would have validated the date value since it is stored in their frontmatter cache, but it apparently is not. I just pushed a fix for all of these bugs. Please try 1.7.1.

**Comment by decaf-dev** [comment]
> When it comes to time, I also want to know what format should be used when filling in the date for the `date/datetime` filter with "is after" condition? ![image](https://private-user-images.githubusercontent.com/4013062/338480427-dc111f0e-050e-49de-9bb0-485868339cc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTU5NjUsIm5iZiI6MTcxODA5NTY2NSwicGF0aCI6Ii80MDEzMDYyLzMzODQ4MDQyNy1kYzExMWYwZS0wNTBlLTQ5ZGUtOWJiMC00ODU4NjgzMzljYzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDg0NzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTljMGRhZGJiNzNlOTE4MTc3ZGJmMzQ3YjUwZjBiMTdlMTc3MzJmOGJkYjliOWJiZTQwYjI3ZmU5NjEwNTRkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oraO4nqvpppYpZVgECDm3jt4cwOAtb8zgEQvELBG7Jk) (Is it possible to add a date selection button later? )
> 
> Also, can it support adaptive dates like 1d (1 day) or 2w (2 weeks) instead of entering a fixed date?

The formats that are supposed by should be `YYYY-MM-DDTHH:mm:ss` or `YYYY-MM-DDTHH:mm` or `YYYY-MM-DD`.

Yes, I can add a date field. I will open another issue for that.

**Comment by Moyf** [comment]
> I thought Obsidian would have validated the date value since it is stored in their frontmatter cache, but it apparently is not. I just pushed a fix for all of these bugs. Please try 1.7.1.

Yeaaaah, Updated to 1.7.1 and it works perfectly now!
