### ISSUE TITLE
Date select button

### ISSUE THREAD

**Issue by decaf-dev** [decaf-dev/obsidian-vault-explorer#68]
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/dc111f0e-050e-49de-9bb0-485868339cc3)
(Is it possible to add a date selection button later? )

Also, can it support adaptive dates like 1d (1 day) or 2w (2 weeks) instead of entering a fixed date?

_Originally posted by @Moyf in https://github.com/decaf-dev/obsidian-vault-explorer/issues/65#issuecomment-2159995384_

**Comment by decaf-dev** [comment]
@Moyf Added in 1.9.0. I copied Notion's date filtering. There is also a custom field now.

**Comment by Moyf** [comment]
Great! Thanks! <3
