### ISSUE TITLE
Add filter: FileName/Folder

### ISSUE THREAD

**Issue by Moyf** [decaf-dev/obsidian-vault-explorer#70]
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/2cc4b103-19c1-488a-af44-d73ea15bbc58)

Hope to add filter for "file name" and "folder (path)"

**Comment by decaf-dev** [comment]
Yep! That is the next thing I am going to work on. Right now the filtering is just properties, I'm going to change it to be general "Advanced filtering" where you can filter based on file content, folder, and tags. File name is also a good idea

**Comment by Moyf** [comment]
> Yep! That is the next feature that I am going to work on. Right now the filtering is just properties, I'm going to change it to be general "Advanced filtering" where you can filter based on file content, folder, and tags. File name is also a good idea

Greeeeat! Looking forward to it very much!

**Comment by Moyf** [comment]
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/93a1798c-d00a-4e69-9b19-79033228c796)

Maybe add a "Duplicate" function for filter preset, so that we can easily replace keywords while keeping other conditions?

**Comment by Moyf** [comment]
Also.. Could you add **Global Filter** in the Plugin Settings?

For example, I don't want to see all my `#daily-note` Notes, and currently I noticed that we can not multi-select filters.
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/4862bed4-7186-4e11-918b-7b5f4551f48a)

So maybe add a global filters list in plugin setting would be more convinient to filter those notes we don't need to see.

**Comment by decaf-dev** [comment]
Added in 1.10.0

**Comment by Moyf** [comment]
Just updated! Great works!

Could you please consider use text input with auto-complete rather than drop-list?

I'm using "FolderNotes" plugin and I got sooooo many folders 😹
So it's kind of hard to find a folder.
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/8e1f8847-b3a9-4764-9a58-f033ed677c86)

An input box with suggestions of folders might be more convinient 
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/9332b328-f9c6-438f-818a-28ec8916eff7)

**Comment by Moyf** [comment]
> Just updated! Great works!
> 
> Could you please consider use text input with auto-complete rather than drop-list?
> 
> I'm using "FolderNotes" plugin and I got sooooo many folders 😹 So it's kind of hard to find a folder. ![image](https://private-user-images.githubusercontent.com/4013062/342262515-8e1f8847-b3a9-4764-9a58-f033ed677c86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDY0MDYsIm5iZiI6MTcxOTMwNjEwNiwicGF0aCI6Ii80MDEzMDYyLzM0MjI2MjUxNS04ZTFmODg0Ny1iM2E5LTQ3NjQtOWE1OC1mMDMzZWQ2NzdjODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMDkwMTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTU1YzhkMWNlZTg5OWJhZjMzYmE4Y2RmZWQ0ZTFmNTA1YWRmNDMzZjMzMDM0YTkxZGEwMTU0MjFiMzFlYzVjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4NH1bDrhMskqWJ7Zj1tBuTZUEOJ12WRrBO_8s2w7JKY)
> 
> An input box with suggestions of folders might be more convinient ![image](https://private-user-images.githubusercontent.com/4013062/342262997-9332b328-f9c6-438f-818a-28ec8916eff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDY0MDYsIm5iZiI6MTcxOTMwNjEwNiwicGF0aCI6Ii80MDEzMDYyLzM0MjI2Mjk5Ny05MzMyYjMyOC1mOWM2LTQzOGYtODE4YS0yOGVjODkxNmVmZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMDkwMTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjllZmIxMGM5YWI1N2QyZWYzOWFlMTQxYjRiMWNmMWI4ZmNjYWIwZDI4YWQ1ZGE4OTFiYmY3ODJhMTdlMzBhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NEHSlxjYiby3vlRzooJwM8fL6GmlsfMK53gsWiJfTVU)

Besides, the very long path of folder would also be a problem:
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/73512289-23a6-4991-a713-901e2d728fb2)
