### ISSUE TITLE
[FR] Random Sorting?

### ISSUE THREAD

**Issue by Moyf** [decaf-dev/obsidian-vault-explorer#77]
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/8318569b-8c28-4614-ac2e-d1022dc58935)

I'm not quite sure, I just happened to think of it so I thought I'd share this idea first. 
Maybe add a "random sort" (and limit the maximum number of notes), so we can quickly review some random notes from our vault?

*GIMME SOME CHAOS HAHA😈*

**Comment by decaf-dev** [comment]
That's an interesting idea. When you say limit the maximum number of notes, how many are you thinking?

I am thinking that having a dedicated view for this may be better. The random sort wouldn't be dependent on any other filters would it?

**Comment by Moyf** [comment]
> That's an interesting idea. When you say limit the maximum number of notes, how many are you thinking?
> 
> I am thinking that having a dedicated view for this may be better. The random sort wouldn't be dependent on any other filters would it?

Well, when I say limit the maximum number of note I was concerning 'bout the performance. Like.. doing random sorting for All the notes might be perform-consuming.. or not?
If the performance is not a problem, then I think the Page size would be enough.
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/acd31f37-83ee-4027-af30-a2b9902a49d3)

For example, I have 4k+ notes, and when I **Random Sort** just show me 50 (page size) of 'em.

---

And I also agree that seperating the **Random** function from the sorting would be better!

I hope to keep the function of the filter. Because there are many notes, some limits would make the result much more useful. 
And the support for filters just provides more options, which we can always choose not to enable.

One (not very sufficient) design I can think of is to add a random button, which, when clicked, will randomly display the current filtering results, and clicking it again will randomize it again.
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/aa7a7897-8878-413c-8b75-0917ffa669bb)

But the final design depends on you!  ; )

**Comment by decaf-dev** [comment]
Added in 1.19.0 :)

**Comment by Moyf** [comment]
> Added in 1.19.0 :)

Good to have it!  :D 
Just updated and tested it, is "re-randomize" is currently supported?
*Similar to "Roll the dice again"*

**Comment by decaf-dev** [comment]
Sorry, it seems like random sort wasn't working at all. A fixed for this will be included in 1.24.0. There will also be a button to "reshuffle"

**Comment by decaf-dev** [comment]
1.24.0 has now been released
