### ISSUE TITLE
Background update Frequency

### ISSUE THREAD

**Issue by Moyf** [decaf-dev/obsidian-vault-explorer#78]
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/75de1cd9-7e9a-4463-a49f-91497a47ead4)

I don't know how frequently it would re-scan the vault, but if I leave this tab in background, it would continuously showing logs.

Could we set the Update frequency.. Or, more importantly, if the Vault Explorer Tab is not active, is it possible to lower the update frequency?

**Comment by decaf-dev** [comment]
It's actually not rescanning the vault. It's just updating timestamp values that are used for filtering. Calling Moment.JS functions are really expensive computationally. The update is set to 1 minute right now.

**Comment by decaf-dev** [comment]
The idea is if you leave the view open, you never have to close it and reopen it to get the latest timestamp filtered data.

**Comment by decaf-dev** [comment]
I think I will also update the way that this system works to only update the view on the appropriate day.

**Comment by decaf-dev** [comment]
By the way, you can also change the logger settings to be `Error` or `Off`. That will also get rid of the messages

**Comment by Moyf** [comment]
> The idea is if you leave the view open, you never have to close it and reopen it to get the latest timestamp filtered data.

Yay definately agree with it!
Roger that :D

**Comment by Moyf** [comment]
> By the way, you can also change the logger settings to be `Error` or `Off`. That will also get rid of the messages

Good to know, thank you!

**Comment by decaf-dev** [comment]
Added a `Enable clock updates` setting in 1.13.0. Feel free to disable it.
