### ISSUE TITLE
Global Filter

### ISSUE THREAD

**Issue by decaf-dev** [decaf-dev/obsidian-vault-explorer#79]
Also.. Could you add **Global Filter** in the Plugin Settings?

For example, I don't want to see all my `#daily-note` Notes, and currently I noticed that we can not multi-select filters.
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/4862bed4-7186-4e11-918b-7b5f4551f48a)

So maybe add a global filters list in plugin setting would be more convinient to filter those notes we don't need to see.

_Originally posted by @Moyf in https://github.com/decaf-dev/obsidian-vault-explorer/issues/70#issuecomment-2164551787_

**Comment by decaf-dev** [comment]
@Moyf Added in 1.11.0

**Comment by Moyf** [comment]
> @Moyf Added in 1.11.0

Oh, it's the "Sticky Group" function, right?
I think it's very well-designed and elegant! 👍🏻

___

BTW I don't know why the filters do not use the whole width 🤔
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/9534bc95-e732-41a2-a048-93d6c29baec9)

Checked the css, it shows `width: unset` 
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/5e683a18-2bbf-4c13-8d55-3b9b65ea8a27)

**Comment by Moyf** [comment]
> > @Moyf Added in 1.11.0
> 
> Oh, it's the "Sticky Group" function, right? I think it's very well-designed and elegant! 👍🏻
> 
> BTW I don't know why the filters do not use the whole width 🤔 ![image](https://private-user-images.githubusercontent.com/4013062/342261469-9534bc95-e732-41a2-a048-93d6c29baec9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTg1NTAsIm5iZiI6MTcxOTIxODI1MCwicGF0aCI6Ii80MDEzMDYyLzM0MjI2MTQ2OS05NTM0YmM5NS1lNzMyLTQxYTItYTA0OC05M2Q2YzI5YmFlYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMDgzNzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmNhZjdiNGVjODJlNWNlNzY4YTE3NGQzMGQ3NzFmNmFkYTUwYjg2ODBiZjk1ZDJhYmU2MjA3MGE0ODUxZDE5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fmjsf3YaDUlbgwdEpj8xLkk8MsK69YVFkqBepWo4IZ8)
> 
> Checked the css, it shows `width: unset` ![image](https://private-user-images.githubusercontent.com/4013062/342261697-5e683a18-2bbf-4c13-8d55-3b9b65ea8a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTg1NTAsIm5iZiI6MTcxOTIxODI1MCwicGF0aCI6Ii80MDEzMDYyLzM0MjI2MTY5Ny01ZTY4M2ExOC0yYmJmLTRjMTMtOGQ1NS0zYjliNjVlYThhMjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMDgzNzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQ0YTA5NGU3NGU3ZWE4YTMxYmZlOTI3NTU5ZDI4NjhhN2QyZWVhOTg0NTg5NGQ4YWI5NDZiNmJlZGUwOTM3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uWcI8NTkEWIDS2gz8YnE6TaugVi1wtrXJ1ZG1k0zgjA)

![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/4013062/226edd4c-f311-4a04-ad68-96fd107ae66e)

Oh, I think it's the reason.

**Comment by decaf-dev** [comment]
Yes, the group's are constrained to keep things more tidy and reduce cognitive load from having something 10 groups appear. Would you prefer to have all groups available though?

**Comment by Moyf** [comment]
> Yes, the group's are constrained to keep things more tidy and reduce cognitive load from having something 10 groups appear. Would you prefer to have all groups available though?

Oh, I think it's OK for me, since I can modify it thru css snippets  ; ) 

Though I did have some other suggestions with the buttons, I think I could open a new issue! (#126 )
