### ISSUE TITLE
Filter not being applied

### ISSUE THREAD

**Issue by muteboy** [decaf-dev/obsidian-vault-explorer#86]
Hi,
I'm using Vault Explorer to view a folder. I have a filter group called "tags includes value", where list property "tags" contains "value".
It appears not to work. When I view the filter group, it displays notes which have this value, and those which do not. Is there a way to refresh the list?

**Comment by decaf-dev** [comment]
Hi @muteboy. Is the toggle for the rule enabled? In addition, is the group enabled? It should appear purple. I will be adding some screenshots and videos to the guide.

<img width="291" alt="image" src="https://github.com/decaf-dev/obsidian-vault-explorer/assets/40307803/6b60e061-2b7f-4b22-b77b-239f9e422ff8">

<img width="555" alt="image" src="https://github.com/decaf-dev/obsidian-vault-explorer/assets/40307803/7b8bd34b-3662-451d-8df1-00d08c82a88d">

**Comment by muteboy** [comment]
Hi, thanks for the quick reply. Here's some shots of a couple of examples.
Filter definitions:
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/10484438/f80a58a3-38ee-48dd-8e87-dcf4b913852a)
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/10484438/638583fc-7f2e-4b02-a81c-69d6864a5a04)
No filters applied, all items visible: 
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/10484438/a9bc2033-f9c6-41e0-95fc-23bd4da839ac)
Only showing items with tag "abbreviation":
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/10484438/2c3e6f5b-88b8-40cf-8775-3c9cb3ba0c11)
Should only show items without tag "abbreviation", but still showing item "ADA" with that tag:
![image](https://github.com/decaf-dev/obsidian-vault-explorer/assets/10484438/e4f492ca-0d68-4fb2-a585-80bb15ba42a8)

**Comment by decaf-dev** [comment]
Hmmm. This is puzzling. Do you happen to have an extra whitespace character after abbreviation?

**Comment by decaf-dev** [comment]
@muteboy Can you try 1.8.1 and see if the issue is still occurring?

**Comment by muteboy** [comment]
Hi,
I'm on 1.11.0 now, and it looks like it's working!
Filter "does not contain 'abbreviation'" now only shows items without that tag,
