### ISSUE TITLE
Fuzzy search support

### ISSUE THREAD

**Issue by lifehaschanged** [decaf-dev/obsidian-vault-explorer#98]
Thanks for your plugin!

Can I ask you if a fuzzy search support is planned?

The Lineage plugin for example has the ability to search with that by a button:

![grafik](https://github.com/decaf-dev/obsidian-vault-explorer/assets/81463128/1da23c0d-b89d-46ca-b20f-f9a497eba473)

https://github.com/ycnmhd/obsidian-lineage

**Comment by decaf-dev** [comment]
It isn't currently planned, but I like this suggestion.
