### ISSUE TITLE
Filter group click inversion setting

### ISSUE THREAD

**Issue by lifehaschanged** [decaf-dev/obsidian-vault-explorer#99]
Thank you for the great filter groups, which significantly simplify finding files. 
I find it fantastic that you can individually activate filter group buttons by holding down the ctrl key and the left mouse button. Additionally, you can activate multiple filter groups simultaneously with a normal mouse click. 
However, I often feel more comfortable navigating if I could reverse this behavior. This means that the left mouse button would only activate a single filter group, and clicking on another filter group would deactivate the currently active one (i.e., the behavior currently achieved by ctrl+left mouse button).
I'd be glad if you could implement a setting for that.
Thanks!

**Comment by decaf-dev** [comment]
Thanks for the feedback. This has been reverted back to its original behavior in 1.13.0. To facilitate multiple groups being active at a time, I have added "sticky groups". Please see the release notes for more information. I will be updating the documentation soon.
